app:
  logFilterCategories: "EventQueue,Dispath"
  debugLevel:  debug

dbpool:
  default: xyt
  xyt:
    database: "${DB_DATABASE}"
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    username: "${DB_USER}"
    password: "${DB_PWD}"
    drive: "mysql"

redisPool:
  default: xyt
  xyt:
    database: 0
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PWD}"
    drive: "mysql"

modules:
  web:
    type: inner
    bindAddr: "${WebAddr}"
    staticHost: "${StaticHost}"
    #staticHost: "/dev"
    #staticHost: "http://data.xyt.xytschool.com"
    staticVersion: "${STATIC_VERSION}"
    viewsRoot: "./resources/views"
    publicRoot: "./resources/public"
    sotragePath: "./resources/storage"
    jwt_key: "${JWT_KEY}"
    allowOrigins:
      - "http://127.0.0.1:8080"
      - "http://m1.laravelschool.xyt"

  MessageModule:
    type: inner
    providers:
      default:
        type: "aliyun"
        region_id: "cn-hangzhou"
        key_id: "${ALIYUN_KEY_ID}"
        key_secret: "${ALIYUN_KEY_SECRET}"
        sign_name: "${ALIYUN_SIGN_NAME}"
        template_code: "${ALIYUN_CODE}"


  #  comment:
  #    type: inner
  #    bindAddr: ${COMMENT_ADDR}

  #  debug:
  #     type: inner

  #  mqtt:
  #      type : inner
  #      productKey : a1GvAwy4lNt
  #      deviceSecret: ulsuWZkXGzOQsR5L5AYUQpQxLKvidmUi
  #      deviceName:  PC1219