app:
  logFilterCategories : "EventQueue,Dispath"
  debugLevel:  debug

dbpool:
   default: xyt
   xyt:
      database: "gateway"
      host: "xytschool.com"
      username: "remote_gw"
      password: "iqojasukk083lwjxw9"
      drive: "mysql"

modules:
#  mqtt:
#      type : inner
#      productKey : a1GvAwy4lNt
#      deviceSecret: ulsuWZkXGzOQsR5L5AYUQpQxLKvidmUi
#      deviceName:  PC1219

  web:
      type : inner
      addr: 0.0.0.0
      port: 8080
      staticFileUrl: "http://127.0.0.1:8080"
      staticFileVersion : "1001"
      viewsRoot: "./views"
      publicRoot: "./public"
      sotragePath: "./storage"
      allowOrigins:
          - "http://127.0.0.1:8080"
          - "http://localhost:10086"
          - "http://127.0.0.1:88"


  debug:
      type : inner